FROM public.ecr.aws/lambda/python:3.11

RUN pip install --no-cache-dir \
    numpy==1.26.4 \
    pandas==2.2.1 \
    pyarrow==15.0.0 \
    scipy==1.11.4 \
    scikit-learn==1.5.2 \
    xgboost==2.0.3 \
    boto3==1.34.0

COPY services/predict/app.py ${LAMBDA_TASK_ROOT}/
COPY services/predict/storage.py ${LAMBDA_TASK_ROOT}/

CMD ["app.lambda_handler"]
